---
title: "US Map 1"
author: "Kelly DeBie"
date: "2022-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r fig.height=10, fig.width=10}

library(tidyverse)  
library(readr)
library(tigris)  
library(plotly)  
library(maps)  
library(ggplot2)  
library(ggthemes)  
library(maptools)
library(scales)  
library(cowplot)
library(googleway) 
library(ggrepel)
library(ggspatial)
library(rnaturalearth) 
library(rnaturalearthdata) 
library(sf)
library(forcats)

altfuel <- read_csv("data/Alternative_Fueling_Stations.csv") 

altfuel <- altfuel %>%
  mutate(fuel_type_code=fct_recode(.f = fuel_type_code,
                                   "Biodiesel"= "BD",
                                   "Compressed Natural Gas" = "CNG",
                                   "Electric" = "ELEC",
                                   "Ethanol" = "E85",
                                   "Hydrogen" = "HY",
                                   "Liquefied Natural Gas"= "LNG",
                                   "Propane" = "LPG"))

world <- ne_countries(scale = "medium", returnclass = "sf")   
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))  


fuelmap <- ggplot(data = world) +
    geom_sf() +
    geom_sf(data = states, fill = NA) +
    geom_point(data = altfuel, aes(x = X, y = Y, col=fuel_type_code), size = 0.8) +
    coord_sf(xlim = c(-130, -65), ylim = c(23, 52), expand = FALSE) + 
    labs(title= "Alternative Fuel Stations in the United States", subtitle= "Contiguous 48", 
         x=element_blank(), y=element_blank()) + 
    guides(colour = guide_legend(override.aes = list(size=5))) +
    scale_color_discrete("Fuel Type") +
    theme_few()
fuelmap   


colorado <- altfuel%>%
  filter(state=="CO")  

co_counties<-counties("Colorado", cb = TRUE)

fuelmapCO <- ggplot(data = world) +
    geom_sf() +
    geom_sf(data = states, fill = NA) +
    geom_sf(data=co_counties, fill = NA) +
    geom_point(data = colorado, aes(x = X, y = Y, col=fuel_type_code), size = 2) +
    coord_sf(xlim = c(-109.5, -101.5), ylim = c(36.5, 41.5), expand = FALSE) + 
    labs(title= "Alternative Fuel Stations in Colorado", 
         x=element_blank(), y=element_blank()) + 
    guides(colour = guide_legend(override.aes = list(size=5))) +
    scale_color_discrete("Fuel Type") +
    theme_few()  

fuelmapCO

```

